Create broadcast group
Mukalawit/PostIt pull request #10
Opened 2022-12-21 13:08 UTC by Mukalawit

2022-12-21 14:08 UTC, Descartess requested changes

2022-12-21 14:08 UTC, Descartess commented on server/__tests__/add-group.tests.js
> +describe('When a user adds a group', () => {
Missing test cases  for would return 401 when a user is not authorised.

2022-12-21 14:08 UTC, Descartess commented on server/models/groups.js
> +    const group = await prisma.$queryRaw`SELECT "id" FROM "Group" WHERE "name" = ${name} AND "groupAdmin" = ${user.id}`;
Is there any particular reason for using raw `SQL` here ?

2022-12-21 14:08 UTC, Descartess commented on server/models/groups.js
> +  async groupByUserExists() {
```suggestion
  async isDuplicate() { 
```

This might be a clearer function name

2022-12-21 14:08 UTC, Descartess commented on server/models/groups.js
> +    const user = verifyAccessToken(token);
In the event that the access token has expired, how would the user know and then react accordingly?

I think as opposed to either returning null or a user. The verify access token should also be able to throw meaningful errors

2022-12-21 14:08 UTC, Descartess commented on server/models/groups.js
> +  async addGroup() {
```suggestion
  async createGroup() {
```

2022-12-21 14:08 UTC, Descartess commented on server/models/groups.js
> +  constructor(name, token) {
```suggestion
  constructor(name,id) {
```

I think we shouldn't couple the group and the token verification logic.  We shouldn't add that dependency.  
Let the group take in `id` explicitly

2022-12-21 14:08 UTC, Descartess commented on server/routes/group/create-broadcast-group.js
> +  }
This would be a good place to verify the user access token as opposed to doing it within the Group model. 

We need to separate these concerns. The beauty about this is that we can move that logic then to middlewares.

2022-12-23 07:38 UTC, Mukalawit commented on server/models/groups.js
> +    const group = await prisma.$queryRaw`SELECT "id" FROM "Group" WHERE "name" = ${name} AND "groupAdmin" = ${user.id}`;
Prisma does not currently support this query option, it has to done this way

2022-12-23 07:38 UTC, Mukalawit commented on server/__tests__/add-group.tests.js
> +describe('When a user adds a group', () => {
Done

2022-12-23 07:39 UTC, Mukalawit commented on server/models/groups.js
> +  async groupByUserExists() {
Done, thanks for the suggestion it is better

2022-12-23 07:48 UTC, Mukalawit commented on server/models/groups.js
> +    const user = verifyAccessToken(token);
It throws the errors, i have just added more body to it

2022-12-23 07:52 UTC, Mukalawit commented on server/models/groups.js
> +  async addGroup() {
Done

2022-12-23 08:08 UTC, Mukalawit commented on server/models/groups.js
> +  constructor(name, token) {
This was an eye opener, hadn't seen the coupling, thanks

2022-12-23 08:09 UTC, Mukalawit commented on server/routes/group/create-broadcast-group.js
> +  }
Done, thanks

2022-12-28 08:57 UTC, Descartess approved these changes

2022-12-28 08:57 UTC, Descartess commented
Looks good

2022-12-29 10:45 UTC, merged